name: Website deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: target
        options:
          - bulerenergy
          - dev.bulerenergy

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3.12"
      - uses: actions/checkout@v4

      - name: Copy .env
        run: |
          php -r "copy('.env.prod', '.env');"
          sed -i "s/<MAIL_USER>/${{secrets.EMAIL_USER}}/g" .env
          sed -i "s/<MAIL_PASSWORD>/${{secrets.EMAIL_PASSWORD}}/g" .env
          sed -i "s/<APP_KEY>/${{secrets.APP_KEY}}/g" .env
          sed -i "s/<APP_DOMAIN>/${{inputs.environment}}/g" .env

      - name: Install PHP Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader
          composer dump-autoload -o

      - name: Generate key
        run: php artisan key:generate

      - name: Install Node Dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          php artisan view:clear

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: serwer2494047.home.pl
          username: ${{secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ inputs.environment }}/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            ./tests
            .editorconfig
            ./artisan
            ./*.json
            ./*.xml
            resources/js/**
            resources/css/**
            ./tests/**
            ./storage/logs/**
            .editorconfig
            composer.lock
            package-lock.json
            package.json
            phpunit.xml
            vite.config.js

